services:
- docker
  
jobs:
  include:
    
    - name: Build and push docker image with the newest kube-version
      if: type = cron AND branch = master
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - TAG=$(echo $TRAVIS_BRANCH | tr "/" "-")

        - bin/image build latest $TAG
        - bin/image test latest $TAG
        - bin/image push latest $TAG

    - name: Build and push docker images for the last 4 minor kube-versions
      if: type = push AND branch = master
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - TAG=$(echo $TRAVIS_BRANCH | tr "/" "-")

        - bin/image build last4minors $TAG
        - bin/image test last4minors $TAG
        - bin/image push last4minors $TAG
