services:
- docker
  
jobs:
  include:
    
    - name: Build and push docker image with the newest kube-version
      if: type = cron 
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

        - bin/image set_versions missing
        - bin/image build
        - bin/image test
        - bin/image push


    - name: Build and push docker images for the last 4 minor kube-versions
      if: type != cron
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

        - bin/image set_versions last4minors
        - bin/image build $TRAVIS_TAG
        - bin/image test $TRAVIS_TAG

        - test -z "$TRAVIS_TAG" || bin/image push $TRAVIS_TAG

