services:
- docker
  
jobs:
  include:
    
    - name: Build and push docker image with the newest kube-version
      if: type = cron
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - TAG=$(echo $TRAVIS_BRANCH | tr "/" "-")

        - bin/build latest $TAG

    - name: Build and push docker images for the last 4 minor kube-versions
      if: type = push
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - TAG=$(echo $TRAVIS_BRANCH | tr "/" "-")

        - bin/build last4minors $TAG
