name: Build and Publish Docker Image

# Controls when the workflow will run
on:
  schedule:
    - cron: '31 3 * * 0'
  pull_request:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Cache Image Versions
        id: cache-versions
        uses: actions/cache@v3
        with:
          path: /tmp/gcloud-kubectl-docker-versions
          key: image-versions

      - name: Build and publish image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
          bin/image set_versions missing;
          bin/image build;
          bin/image test;

  publish:
    runs-on: ubuntu-22.04
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Cache Image Versions
        id: cache-versions
        uses: actions/cache@v3
        with:
          path: /tmp/gcloud-kubectl-docker-versions
          key: image-versions

      - name: Build and publish image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
          bin/image publish;
